import { Container } from '@mui/system'
import React from 'react'
import Footer from '../layout/Footer'
import Header from '../layout/Header'

const Terms = () => {
    return (
        <>
            <Header />
            <section className='py-5 mt-5 my-5 px-md-4 mx-md-4 text-white privacy'>
                <Container>
                    <div>
                        <p className='text-center mx-auto my-5 fw-bold fs-1'>Terms of Service</p>
                    </div>
                    <div>
                        <p>
                            This document is an electronic record in terms of Information Technology Act, 2000 and rules made there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of our website ‘www.Growpital.com’; (hereinafter referred to as the “Website”). The Website is an internet-based asset ownership portal owned and operated by Farm Silo Tech LLP (hereinafter, referred to as “we”, “us”, “our” and “Growpital”).

                            For the purpose of these User Terms (defined hereinafter), “you”, “your” or “User” refers to any natural or legal person (whether a registered user or otherwise) who accesses the Website, its contents and uses the services offered by Growpital on or through the Website.
                        </p>
                        <p>
                            Growpital is not a registered broker-dealer, investment advisor, lender, and/or money transfer service and does not conduct any activity that would require such registration or certification from any agency including SEBI. Growpital does not provide any kind of investment consultation or any such services. Please read all document carefully before you access or use the service. By accessing, registering at the site, and or using Growpital services you agree to be bound by the terms and conditions set forth below. If you do not wish to be bound by these terms and conditions, please do not access or register for our site and/or engage in any activity conducted by Growpital. if you violate any of these terms of service (which include by reference Growpital’s privacy policy), or otherwise violate an agreement between you and us, Growpital may, apart from initiating any legal proceedings, terminate your privileges, delete your profile and any content or information that you have posted on the site and/or prohibit you from using or accessing the service or the site (or any portion, aspect or feature of the service or the site), at any time in its sole discretion, with or without notice. It is stated that ‘Growpital’ and ‘Project Entities’ or ‘Assets’ are separate legal entities. The Investors will become limited Partners to the said project entities or assets listed over Growpital. Growpital provides just a platform to invest/transfer amount to these project entities for taking fractional ownership of these project in form of partnership shares. The Investors are requested to assess all the Risks & Consent Agreement, LLP Agreement and Non-Disclosure Agreement thoroughly before making the investment in the listed Opportunities.
                        </p>
                        <p>
                            Growpital is just a platform (read software/webapp) where different project entities, working in the agriculture domain, have listed their ownership fractions in the form of LLP Capital Contribution. The entities are registered as LLPs only, and no “Equities” are involved where SEBI’s regulation is required. For the purpose of collecting the amount, the project entities have prepared an Escrow Agreement with Growpital (Farm Silo Tech LLP) and also have an MoU in place for the same. As an investor/user when you invest through Growpital, you will become a partner and lender to these LLPs (as selected by you) and represent your investment. Your partnership stake in the LLP will represent the amount of investment (Capital Contribution and Loan) made by you. Growpital and the designated partners of these LLPs would be responsible for management of these Project Entities on behalf of investors/users. Growpital charges a commission from these Project Entities for providing them the platform. The Escrow Agreement ensures that the user gets the partnership in the project entity when the amount gets transferred to a particular entity and also ensures the distribution of profits, repayment of loan and other payouts given by the Project Entities to the partners. The investor/user signs a consent letter for becoming a partner to the respective LLP/Project Entity, when transferring the amount and signing of the consent letter should be considered as becoming a partner in the LLP for which the required filings will be done with RoC.
                        </p>
                        <p>
                            Your use of our Website and its related sites, services and tools is governed by the terms and conditions as contained in this agreement applicable to the Website (“User Terms”). By using the Website, you have impliedly agreed and accepted these User Terms. If you do not agree or are not willing to be bound by the terms and conditions of these User Terms (and the rules and policies displayed on the Website), please do not click on the [“Accept” button and do not seek to obtain access to or otherwise use the Website. As long as you comply with the provisions of these User Terms, we grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website. If you do not agree to these User Terms, you agree that your sole and exclusive remedy is to discontinue using the Website. Your compliance with these User Terms is a condition to your right to access the Website. Your breach of any provision of these User Terms will automatically, without the requirement of notice or other action, revoke and terminate your right to access the Website.
                        </p>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3' >REGISTRATION ON THE WEBSITE:</p>
                        <ol>
                            <p>
                                You must be at least 18 (eighteen) years of age or older (in case you are an individual), have a sound mind and not debarred by any law to contract in order to access and use the Website. If you use the Website or the Services on behalf of someone else (including but not limited to, as a legal representative of another individual or an entity, you must be authorized by such individual or entity. Our Website is accessible to children under the age of 18 (eighteen), however Growpital strongly encourages parents and guardians to supervise the online activities of their minor children and consider using parental control tools. These tools also can prevent minors from disclosing their name, address, and other personally identifiable information online without parental permission.
                            </p>
                            <p>
                                The Website and the offerings therein are intended only for registered Users who have completed the registration process and completed the KYC (Know-Your-Customer) requirements set out on the Website. A User must agree to become a member of the Website by providing ‘Registration Data’ (as set out on the Website) while registering on the Website and accept these User Terms. The use of the Website is offered to you conditioned on your ‘Acceptance’ of all the terms, conditions and notices contained in these User Terms. Upon ‘Acceptance’, these User Terms will be effective and binding upon you along with any amendments made by website at its sole discretion and posted on the Website and you will not claim invalidity of these User Terms merely on the grounds that this MOU is being concluded electronically. For the aforesaid purposes, ‘Acceptance’ will mean your affirmative action in clicking on [“Accept”] button as provided on the registration page or any act which reflects your use of the Website or the services provided by the Website or any such other actions that implies your acceptance.
                            </p>

                            <p>
                                Upon completion of the registration process, the User will be allocated a unique identification username (“User ID”) to become Registered User. Further, the User may be required to enter the unique one-time password (“OTP”) issued by Growpital to the User for authentication of your User ID each time he/she/it intend(s) to use the Website. You will be responsible for all activities that occur under your User ID or account. Growpital will not be liable to any person for any loss or damage which may arise as a result of any failure by the User to protect their User ID and/or the OTP. You undertake to immediately notify Growpital of any unauthorized use of your account or any other breach of security. You undertake to not sell or otherwise transfer your account/ User ID, or allow any third party to use or access your user account. Growpital reserves the right to refuse service, terminate accounts, or remove or edit content in its sole discretion. You confirm and acknowledge that by registering on the Website, you authorize and consent to Growpital sending promotional and marketing content to you through emails, phone calls, short message service or other electronic and non-electronic mode of communication, and no such communication shall be deemed to be in violation of law relating to unsolicited commercial communication.
                            </p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>USER RIGHTS ON THE WEBSITE:</p>
                        <ol>
                            <p>
                                These User Terms govern your access and use of the Website, which includes any images, text, illustrations, designs, icons, photographs, programs, music clips, downloads, systems and methods of trading, video clips, graphics, user interfaces, visual interfaces, information, data, tools, products, written materials, services and other content (together, “Content”), including but not limited to the design, structure, selection, coordination, expression and arrangement of the Content available on or through the Website. Growpital grants you a limited right to use the Website. The individual user will not use the Website in any way that is fraudulent or unlawful. Your right to use the Website is subject to your agreement to abide by these User Terms in their entirety, as well as any other rules, procedures, policies, terms or conditions that govern all or any portion of the Website. At any time and for any reason Growpital may revoke your right to use all or any portion of the Website. The Website and the Content is not intended for distribution to, or use by, any person or entity in any jurisdiction or country outside India.
                            </p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>WEBSITE SECURITY:</p>
                        <ol>
                            <p>
                                You may not violate or attempt to violate the security of the Website. Tampering with any portion of the Website, providing untruthful or inaccurate information, misrepresenting your identity, or conducting fraudulent activities on the Website, whether or not through the use of agents, are prohibited and constitute a breach of these User Terms. You are prohibited from violating or attempting to violate the security of the Website.<br />

                                You agree to, amongst others, not to (a) license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Website; (b) access the Website in order to build a similar or competitive service; (c) copy, reproduce, distribute, republish, download, displayed, poste or transmit in any form or by any means, any Content of the Website (d) use the Website in any way that causes, or may cause, damage to the Growpital, the Website, its Users or impair the availability or accessibility of the Website in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity; (e) abuse, harass, impersonate, intimidate or threaten other Users; (f) post or transmit, or cause to be posted or transmitted, any content that is harmful, infringing, libellous, defamatory, abusive, offensive, obscene, pornographic, paedophilic, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or otherwise violates any applicable law or right of any third party; or that threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nations; (g) use the Website for any unauthorized purpose, or in violation of any applicable law or these User Terms; (h) post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain access to another User’s account, or private information from any User; (i) infringe upon the IP Rights of Growpital or any third party; (j) submit comments linking to affiliate programs, multilevel marketing schemes, sites repurposing existing stories or off-topic content; (k) post, email, transmit, upload, or otherwise make available any material that contains software viruses or any other computer code, trojan horse or other code with malicious, disruptive and/or destructive features, files or programs designed or functioning to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment, including the Website; (l) use any robot, spider, scraper, sniping software or other automated means to access the Website for any purpose; (m) conduct any systematic or automated data collection activities on or in relation to the Website (n) use the Website or any Content any part of it to transmit or send unsolicited commercial communications, or for any other purposes related to marketing; (o) reverse engineer, frame, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software obtained from or part of the Website; (p) disable, remove, defeat, or avoiding any security device or system, including, without limitation, any login functionality used to authenticate Users; (q) attempt to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (r) attempt to interfere with service to any user, host or network, including, without limitation, via means of submitting a virus to the Website, overloading, “flooding” ,”spamming”, “mailbombing” or “crashing” (s) remove any notices, warnings, labels, annotations or instructions from any portion of the Website or any related material, including, without limitation, any patent, trademark, copyright, or other proprietary notices or license provisions; or (t) otherwise invading the privacy of, obtaining the identity of, or obtaining any personal information about any user of the Website. Any violations of system or network security including attempts to intentionally access a computer without authorization or exceed your authorized access level may result in civil and criminal charges, including but not limited to charges under applicable laws. Growpital may investigate occurrences that might involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations. We may, without prior notice or warning of any kind, restrict or terminate the access of any and all users to the Website if we reasonably conclude that such restriction or termination is necessary to prevent, or prevent the further spread, of a virus, security breach or system malfunction. The Website may contain certain links. Activating links on the Website may cause individual users to leave the Website. Such links are provided solely for individual users’ convenience and information. Growpital has not reviewed any of the websites linked with or connected to the Website and using links on or to the Website is at each individual user’s own risk.
                            </p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>OWNERSHIP OF MATERIALS ON WEBSITE</p>
                        <ol>
                            You may download or copy Content only to the extent such download is expressly permitted in writing on the Website. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Content, the Website or any related software. Nothing on the Website will be interpreted as granting any license or right to use any image, trademark, trade dress, logo or service mark on the Website. Anything transmitted to the Website by you becomes Growpital’s property and may be used by us for any lawful purpose. Growpital reserves all rights with respect to copyright and trademark ownership of all material on the Website, and will enforce such rights to the full extent of the law. Unless otherwise noted, all Contents are copyrights, trademarks, trade dress and/or other intellectual property owned, controlled or licensed by Growpital or by third parties who have licensed their materials to Growpital and are protected by Indian and international copyright laws. The compilation of all Contents on the Website is the exclusive property of Growpital and is also protected by Indian and international copyright laws. The Website, including all Information, is owned by or licensed to Growpital and is subject to and protected by various intellectual property rights, including but not limited to copyright, trade secrets, trademarks, service marks, brand names and other proprietary rights whether under contract, statute or any similar provisions (“IP Rights”). All IP Rights are and will remain the exclusive property of Growpital, its respective third-party licensors or third parties to whom it is attributed and in using the Website individual users will not obtain any rights, title or other interest in or to any information on the Website or related IP Rights. Subject to the above, individual users are entitled to view the Information on the Website and to copy and print such information for personal use. Individual users are not permitted to sell or distribute or otherwise deal with the Information on the Website or any deviations of such information without the prior written consent of Growpital. The Website uses different web analytics service and is compliant with their terms and conditions.
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>NO OFFERS OR RELIANCE</p>
                        <ol>
                            <p>The Website has been prepared solely for purposes of information. The information available on the Website is for convenience of presentation and under no circumstances should the Website be used or considered as an offer to sell or the invitation or solicitation of an offer to buy any asset listed on the Website. Before making a decision with respect to purchasing any asset, Users are advised to carefully read the related final documentation. Further, Growpital does not give or offer any business advice, investment advice, tax or legal advice to anyone using this Website. Accordingly, Users are advised to consult with their tax, legal and financial advisors and carry out their own due diligence with respect to purchasing any asset. Nothing contained on the Website must be relied upon as a promise or representation as to past or future performance. The Website may contain forward-looking statements. In some cases, you can identify forward-looking statements by terminology such as “may,” “will,” “should,” “expects,” “plans,” “;anticipates,” “believes,” “targeted,” “projected,” “underwritten” “estimates” “predicts,” & “potential,” or “;continue”; or the negative of these terms or other comparable terminology. These forward-looking statements include, but are not limited to, statements concerning the company, property, risk factors, plans and projections. Forward-looking statements are subject to various risks and uncertainties. Accordingly, there are or will be important factors that could cause actual outcomes or results to differ materially from those indicated in these statements. None of Growpital, the issuer nor any other person or entity assumes responsibility for the accuracy and completeness of forward-looking statements. Users should conduct their own due diligence and not rely on the financial assumptions or estimates that are displayed on the Website. Assets displayed on the Website are not bank deposits, are not insured and are not guaranteed by Growpital, and may lose value.</p>
                        </ol>
                    </div>
                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>DISCLAIMER</p>
                        <ol>
                            <p>You understand and acknowledge that purchase of the assets listed on the Website is speculative in nature and involves a high degree of risk, including the risk of loss of capital, and is not guaranteed. The Website is suitable only for sophisticated investors who fully understand and are capable of bearing the risks of purchasing such assets. A User should only purchase assets if he/she is able to withstand a total loss of capital. No guarantee or representation is made by us that you will achieve your investment objectives or will receive a return of your capital. Growpital does not endorse or promote any of the opportunities that appear on this Website nor make any recommendations regarding same to any User. Users must not construe anything on the Website as investment, business, legal or tax advice and the content contained herein does not constitute an offer by Growpital to sell, solicit or make an offer to buy an investment interest. Any information made available from our Website, does not represent a solicitation of an offer to buy or sell any property.</p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'> REPRESENTATIONS AND WARRANTIES </p>
                        <ol>
                            <p>By Using this Website, you represent and warrant that:</p>
                            <ol type='1'>
                                <li>You are a citizen of India or, in case of juridical persons, are formed under the applicable laws of India;</li>
                                <li>You are 18 years of age or older and that your use of the Website will not violate any applicable law or regulation;</li>
                                <li>During registration as a User on the Website, you have provided information, which is true, accurate, current, complete and updated about yourself;</li>
                                <li>You will use the Website solely for your personal and non-commercial use. Any use of this Website or its content other than for personal purposes is strictly prohibited.</li>
                            </ol>
                        </ol>

                    </div>
                    <div>
                        <p>USER COVENANTS:</p>
                        <ol>

                            <p className='fw-semibold fs-5 pb-0 pt-3'>When communicating with Growpital through digital media, please:</p>
                            <ol type='1'>
                                <li>Confirm you are visiting the authorised Website;</li>
                                <li>Maintain confidentiality of your User ID and OTPs. Growpital’s Website is private, available only to Users through secure log-in procedures. Apart from allowing you to use your User ID and OTP to enter the Website, Growpital or its representatives will never ask you for your User ID and/or OTP.</li>
                                <li>Do not communicate or deal with personnel who are not affiliated with Growpital.</li>
                                <li>Do not send emails to anyone with an address other than the authorized Growpital e-mail addresses. Growpital does not permit our employees and authorized representatives to send or receive work related emails from personal accounts or any other address.</li>
                            </ol>
                        </ol>

                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>EFFECT ON OTHER AGREEMENTS</p>
                        <ol>
                            <p>
                                Nothing contained in these User Terms is intended to modify or amend any other written agreement you may have with Growpital or other Users of the Website (Other Agreements if any, that may currently be in effect. In the event of any inconsistency between these User Terms and any Other Agreements, the Other Agreements will govern. Some pages within the Website contain supplemental terms and conditions and additional disclosure and disclaimers, which are in addition to these User Terms. In the event of a conflict, the supplemental terms and conditions and additional disclosures and disclaimers will govern for those sections or pages.</p></ol>
                    </div>
                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>INDEMNITY</p>
                        <ol>
                            <p>
                                You agree to indemnify and hold harmless Growpital and (as applicable) its subsidiaries, affiliates, third-parties and their respective shareholders, officers, directors, agents, and employees, from any losses, liabilities, damages, costs and expenses, claims or demand, or actions including reasonable attorneys fees asserted against or incurred by Growpital, made by any third party arising out of your breach or non-performance of terms of these User Terms, or the documents they incorporate by reference, or your violation of any law, rules or regulations or the rights of a third party.
                            </p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>CHANGES TO THESE TERMS</p>
                        <ol>
                            <p>
                                We reserve the right to update (change, modify, add and/or delete) these User Terms from time to time, at our sole discretion, to reflect company initiatives, changes in the law or technology or changes in our practices. When we update these User Terms, we will intimate you of the amendments on your email address or on the Website. If you do not agree to the amendments, please do not use the Website any further. By continuing to use the Website, you will be deemed to have consented to the latest version of these User Terms.
                            </p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>MISCELLANEOUS</p>
                        <ol>
                            <p>General None of the provisions of these User Terms will be deemed to constitute a partnership or agency between you and Growpital and you will have no authority to bind Growpital in any manner whatsoever.</p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>Notices</p>
                        <ol>
                            <p>
                                All notices and other communications required or permitted hereunder to be given to a party will be in writing, in the English language, and will be sent e-mail, or mailed by prepaid internationally- recognized courier or otherwise delivered by hand or by messenger, addressed to such party’s address as set forth below or at such other address as the party will have furnished to the other party in writing in accordance with this provision: If to Growpital:  <a href="mailto:support@Growpital.in" style={{ color: "#07e57d", textDecoration: "none" }}>support@Growpital.com.</a>  If to You: At the email address provided by You.
                            </p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>Severability</p>
                        <ol>
                            <p>If any clause of these User Terms is deemed invalid, void or for any reason unenforceable, such clause will be severable and will not affect the validity and enforceability of the remaining clauses of these User Terms.</p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>Entire Agreement:</p>
                        <ol>
                            <p>These User Terms set forth the entire understanding and agreement between you and Growpital with respect to the subject matter hereof.</p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>Assignment</p>
                        <ol>
                            <p>You cannot assign or otherwise transfer your rights or obligations under these User Terms to any third party. Growpital may transfer its rights and obligations (also known as “assign”) under these User Terms without your prior express consent, provided that Growpital will assign these User Terms on the same terms or terms that are no less advantageous to you.</p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>Arbitration</p>
                        <ol>
                            <p>If any dispute arises between you and Growpital during your use of the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of these User Terms, or the documents they incorporate by reference, the dispute will be referred to a sole Arbitrator who will be an independent and neutral third party identified by Growpital. The place of arbitration will be Jaipur, Rajasthan. The arbitration proceedings will be in the English language and will be governed by Arbitration & Conciliation Act, 1996.</p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>Governing Law:</p>
                        <ol>
                            <p>These User Terms or the documents they incorporate by reference will be governed and construed in accordance with the laws of India. Subject to clause of Arbitration above, all disputes arising under these User Terms between you and Growpital will be subject to the exclusive jurisdiction of courts at Jaipur, Rajasthan, India.</p>
                        </ol>
                    </div>

                    <div>
                        <p className='fw-semibold fs-5 pb-0 pt-3'>Refunds & Cancellations</p>
                        <ol>
                            <p>Since we are a platform to list project assets, all refunds and cancellations will be notified to project entities. The project entities will process/transfer the originally invested amount for getting the fractional ownership of the farm project asset, immediately to your wallet as per the date of withdrawal request in lines with lock-in period, which you can withdraw anytime in your bank account. Please note that when any cancellation will be done, you will have to give up fractional ownership of the project entity you own by investing in that particular project asset.</p>
                        </ol>
                    </div>
                </Container>
            </section>
            <Footer />
        </>
    )
}

export default Terms