import React from 'react'
import { Accordion, Col, Row } from 'react-bootstrap';

const AccordingQue = (props) => {
    const AccorianItems = [
        {
          Id: "0",
          Title: "What is Growpital? (In a Nutshell)",
          SubTitle:
            "The all-new Agro investment platform with tax-free income. It’s the new clutter-free, fixed-income platform with ESG benefits for smart investors giving a whopping 8% -16% fixed returns.",
        },
        {
          Id: "1",
          Title: "How does Growpital works?",
          SubTitle:"- Choose your investment plan and units of investments in farm projects.",
          SubTitle1:"- Choose your investment plan and units of investments in farm projects.",
          SubTitle2:"- Choose your investment plan and units of investments in farm projects.",
        },
        {
          Id: "2",
          Title: "How does this help farmers and land owners?",
          SubTitle:
            "Farmland owners and farmers are essential stakeholders to obtaining the desired farm productivity. While our model strategically revolves around crop diversification and hedging to predict and produce in-demand crops, we also provide fixed returns to land owners in form of land lease and employment to farmers, directly enhancing farmer’s income and generating higher returns for land owners and investors alike.",
        },
        {
          Id: "3",
          Title: " Is the profit really fixed or there's a catch? ",
          SubTitle:
            "The profits that Growpital provides on your investments is absolutely fixed, without any catch, this happens because the profits are distributed as advance share to the fractional owners from the revenues generated by the farm projects.",
        },
      ];
  return (
    <Row>
    <Col xs={12} md={12}  className="text-center text-md-end" >
    <Accordion defaultActiveKey="0" className="home-accordian"  >
      {AccorianItems.map((Items) => (
        <Accordion.Item
          eventKey={Items.Id}
          key={Items.Id}
          className="mb-3 bg-transparent"
        >
          <Accordion.Header className="text-white fw-600 fs-22">
            <span className={props.Display_Sr_No}>0{Items.Id}</span>{" "}
            {Items.Title}
          </Accordion.Header>
          <Accordion.Body>
            <ul type="none">
              <li className='py-2'>{Items.SubTitle}</li>
              <li className='py-2'>{Items.SubTitle1}</li>
              <li className='py-2'>{Items.SubTitle2}</li>
            </ul>
          </Accordion.Body>
        </Accordion.Item>
      ))}
    </Accordion>
  </Col>
  </Row>
  )
}

export default AccordingQue