import React from "react";
import { Accordion, Col, Container, Row } from "react-bootstrap";

const FaqsAccordian = (props) => {
    const AccorianItems = [
        {
            Id: "0",
            Title: "What is Growpital? (In a Nutshell)",
            SubTitle:
                "The all-new Agro investment platform with tax-free income. It’s the new clutter-free, fixed-income platform with ESG benefits for smart investors giving a whopping 8% -16% fixed returns.",
        },
        {
            Id: "2",
            Title: " How does Growpital works?",
            SubTitle:
                "- Choose your investment plan and units of investments in farm projects.- Confirm details and pay securely. Our team handles administration and property management – from crop selection, farm inputs, to working with local farmers and improving soil sustainability. Get your fixed payouts every financial quarter end. You can withdraw this directly in your bank account or even choose to re-invest for more wealth creation.",
        },
        {
          Id: "2",
          Title: " How does this help farmers and land owners?",
          SubTitle:
            "Farmland owners and farmers are essential stakeholders to obtaining the desired farm productivity. While our model strategically revolves around crop diversification and hedging to predict and produce in-demand crops, we also provide fixed returns to land owners in form of land lease and employment to farmers, directly enhancing farmer’s income and generating higher returns for land owners and investors alike.",
        },
        {
          Id: "3",
          Title: " Is the profit really fixed or there's a catch? ",
          SubTitle:
            "The profits that Growpital provides on your investments is absolutely fixed, without any catch, this happens because the profits are distributed as advance share to the fractional owners from the revenues generated by the farm projects.",
        },
      ];
      const Accorian2Items = [
        {
          Id: "0",
          Title: "Who are the farmers for growpital?",
          SubTitle:
            "We have a dedicated team of highly experienced farmers, farm managers and experts who make their hands and legs dirty in the farms day and night in order to grow in-demand crops that can yield high profitability.There’s a detailed procedure of selecting the farmers and farms we choose to partner with.",
        },
        {
          Id: "1",
          Title: " How are you able to give such good returns?",
          SubTitle:
            "We have a detailed and highly meticulous procedure of curating farmlands and a research-based system for selecting the type of horticultural crops that we grow. Think of it as a mutual fund, where diversified crops are grown over the farm projects instead of equities and bonds.This, along with a deep understanding of market demand and a strong network of buyers allow us to receive great profits and therefore enables us to pass those on to investors.",
        },
        {
          Id: "2",
          Title: " Who manages the farm projects?",
          SubTitle:
            "The farm projects are owned and developed by us and are operated in two ways:- Our in-house team who follows the schedule to grow crops and sell it in market- We get into an operational partnership with established or experienced players in market and get fixed revenue from them.",
        },
      ];
    return (
        <>
            <Container>
                <Row>
                    <Col md={6}> <Accordion defaultActiveKey="0" className="faqs-accordian" >
                        {AccorianItems.map((Items) => (
                            <Accordion.Item
                                eventKey={Items.Id}
                                key={Items.Id}
                                className="mb-3 bg-transparent"
                            >
                                <Accordion.Header className="text-white fw-600 fs-22">
                                    {/* <span className={props.Display_Sr_No}>0{Items.Id}</span>{" "} */}
                                    {Items.Title}
                                </Accordion.Header>
                                <Accordion.Body>{Items.SubTitle}</Accordion.Body>
                            </Accordion.Item>
                        ))}
                    </Accordion></Col>
                    <Col md={6}> <Accordion defaultActiveKey="1" className="faqs-accordian" >
                        {Accorian2Items.map((Items) => (
                            <Accordion.Item
                                eventKey={Items.Id}
                                key={Items.Id}
                                className="mb-3 bg-transparent"
                            >
                                <Accordion.Header className="text-white fw-600 fs-22">
                                    {/* <span className={props.Display_Sr_No}>0{Items.Id}</span>{" "} */}
                                    {Items.Title}
                                </Accordion.Header>
                                <Accordion.Body>{Items.SubTitle}</Accordion.Body>
                            </Accordion.Item>
                        ))}
                    </Accordion></Col>

                </Row>
            </Container>
        </>
    );
};

export default FaqsAccordian;
